config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: %i(new create destroy index show)
  resource :session, only: [:new, :create, :destroy]
  resources :goals 
  resources :comments, only: %i(new create)
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id               :integer          not null, primary key
#  body             :text             not null
#  commentable_type :string
#  commentable_id   :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class Comment < ApplicationRecord 
  validates :body, presence: true

  belongs_to :commentable, :polymorphic => true
end 

app/models/concerns/commentable.rb
module Commentable 
  extend ActiveSupport::Concern 

  included do 
    has_many :comments, :as => :commentable
  end 
end 

app/models/goal.rb
# == Schema Information
#
# Table name: goals
#
#  id          :integer          not null, primary key
#  title       :text             not null
#  user_id     :integer          not null
#  description :string           not null
#  completed   :boolean          default("false")
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  private?    :boolean          default("false")
#

class Goal < ApplicationRecord 
  include Commentable
  validates :title, :user_id, :description, presence: true 

  belongs_to :author, 
    class_name: 'User',
    foreign_key: :user_id
end 

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  cheers          :integer
#

class User < ApplicationRecord
  include Commentable

  attr_reader :password 

  validates :email, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :email, uniqueness: true
 
  has_many :goals 
  

  after_initialize :ensure_session_token

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)

    return user if user && user.is_password?(password)
    nil
  end 

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end 

  def generate_session_token 
    SecureRandom.urlsafe_base64(16)
  end 

  def reset_session_token! 
    self.session_token = generate_session_token
    self.save!

    self.session_token
  end 

  def ensure_session_token 
   self.session_token ||= generate_session_token
  end 

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :signed_in?
  protect_from_forgery with: :exception


  def log_in(user)
    @current_user = user 
    session[:session_token] = user.session_token
  end 

  def current_user 
    return nil if session[:session_token].nil?
    @current_user ||= User.find_by(session_token: session[:session_token])
  end 

  def signed_in?
    !current_user.nil?
  end 

  def log_out 
    current_user.try(:reset_session_token!)
    session[:session] = nil 
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController 
  def new 
    @comment = Comment.new
  end 

  def create 
    @comment = Comment.new(comment_params)

    if @comment.save
      flash[:notice] = "Comment Added!"
      redirect_to request.referrer
    else
      flash.now[:errors] = @comment.errors.full_messages 
      redirect_to request.referrer
    end
  end 

  private 

  def comment_params 
    params.require(:comment).permit(:body, :commentable_id, :commentable_type)
  end 
end 

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  
  def index 
    @goals = Goal.all 
    render :index
  end 

  def new 
    @goal = Goal.new 
    render :new 
  end 

  def create 
    @goal = Goal.new(goals_params)
    @goal.user_id = current_user.id 

    if @goal.save
      
      redirect_to goal_url(@goal)
    else
      
      flash.now[:errors] = @goal.errors.full_messages
      render :new 
    end
  end

  def show 
    @goal = Goal.find(params[:id])
    render :show
  end 

  def edit 
    @goal = Goal.find(params[:id])

    render :edit
  end 

  def update 
    goal = Goal.update(params[:id], goals_params)
     
    if goal.save!
      flash[:notice] = "Goal Updated!"
      redirect_to request.referrer
    else 
      flash.now[:errors] = goal.errors.full_messages
      render :edit
    end 
  end 

  def destroy 
    @goal = Goal.find(params[:id])

    if @goal.destroy
      flash[:notice] = "Goal Deleted!"
      redirect_to user_url(@goal.user_id)
    else 
      flash.now[:errors] = goal.errors.full_messages
      render :edit
    end 
  end 

  private

  def goals_params 
    params.require(:goal).permit(:title, :description, :private?, :completed)
  end 
end 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController 
  #loging in a current user 
  
  def new 
    render :new
  end 

  def create 
      user = User.find_by_credentials( 
        params[:user][:email], 
        params[:user][:password]
      )

    if user.nil? 
      flash.now[:errors] = user.errors.full_messages
      render new_session_url

    else 
      log_in(user)
      redirect_to user_url(user)

    end 
    
  end 

  def destroy 
    log_out
    redirect_to users_url
  end 
end 

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
  
  def index 
    render :index
  end 

  def new 
    @user = User.new 
    render :new
  end 

  def create 
    @user = User.new(user_params)

    if @user.save 
      log_in(@user)
      redirect_to users_url
      
    else
      flash.now[:errors] = @user.errors.full_messages

      render :new
    end
  end 


  def show 
    @user = User.find(params[:id])
    render :show
  end 

  

  private 

  def user_params
    params.require(:user).permit(:email, :password)
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/comments/_new.html.erb
<form action="<%= comments_url %>" method="POST">
  <input 
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

    <input 
      type="hidden" 
      name='comment[commentable_id]'
      value="<%= commentable.id %>">

    <input 
      type="hidden" 
      name='comment[commentable_type]'
      value="<%= commentable.class %>">

    <label for='comment_id'>Comment:</label>
    <textarea name='comment[body]' id='comment_id'></textarea>

    <input type="submit" value="comment">
</form>

app/views/goals/_delete.html.erb
<form action="<%= goal_url(goal) %>" method="POST">
  <input type="hidden" name="_method" value="DELETE">
  <input 
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <input type="submit" value="Delete '<%= goal.title %>'">
</form>

app/views/goals/_edit.html.erb
  <form action="<%= goal_url(goal) %>" method="POST">
      <input type="hidden" name="_method" value="PATCH">
      <input 
        type="hidden"
        name="authenticity_token"
        value="<%= form_authenticity_token %>">

      <% if goal.completed %>
        <input type="hidden" name="goal[completed]" value="false">
        <input type="submit" value="Ops didn't complete">
      <% else %>
        <input type="hidden" name="goal[completed]" value="true">
        <input type="submit" value="Complete">
      <% end %>
  </form>   

app/views/goals/index.html.erb
<h1>All the Goals!</h1>
<% @goals.each do |goal| %>
 <p> <%= goal.title %> </p>
<% end %>

app/views/goals/new.html.erb
<h1>New Goal</h1>


<form action="<%= goals_url %>" method="POST">
  <input 
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <label for="goal_title">Title:</label>
  <input type="text" name="goal[title]" id="goal_title">
  <br>

  <label for="goal_description">Description:</label>
  <br>
  <textarea rows="4" cols="20" name="goal[description]" id="goal_description"></textarea>
  <br>

  <label for="goal_private">Private?</label>
  <input type="checkbox" name="goal[private?]" value="true" id="goal_private">
  <br>

  <label for="goal_completed">Completed?</label>
  <input type="checkbox" name="goal[completed]" value="true" id="goal_completed">
  <br>

  <input type="submit" value="New Goal">
</form>

app/views/goals/show.html.erb
<h3>Goal:</h3>

<% if !@goal.comments.nil? %>
  <% @goal.comments.each do |comment| %>
    <p> <%= comment.body %> <p>
  <% end %>
<% end %>

<%= render 'comments/new', commentable: @goal %>

<table style="width:10%">
  <tr>
    <td>Title:</td>
    <td><%= @goal.title %></td>
  </tr>
  <tr>
    <td>Details:</td>
    <td><%= @goal.description %></td>
  </tr>
  <tr>
    <td>Visability:</td>
    <td><%= @goal.private? %></td>
  </tr>
  <tr>
    <td>Finished?:</td>
    <td><%= @goal.completed %></td>
  </tr>
  <% if current_user.id == @goal.user_id %>
  <tr>
    <td>Completed?</td>
    <td><%= render 'edit', goal: @goal %></td>
  </tr>
  <% end %>
  
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoalApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>GoalApp</h1>

    <% if !flash[:notice].nil? %>
      <p> <%= flash[:notice] %>  <p>
    <% end %>

    <% if !flash.now[:errors].nil? %>
      <ul>
       <% flash.now[:errors].each do |error| %> 
          <li> <%= error %> </li>
       <% end %>
      </ul>
    <% end %>

    <% if signed_in? %>
    <p>Welcome <%= current_user.email %> <p>

    <form action="<%= user_url(current_user) %>" method="GET">
      <input type="submit" value="Profile">
    </form>

    <form action="<%= session_url %>" method="POST">
      <input 
        type="hidden" 
        name="authenticity_token"
        value="<%= form_authenticity_token %>">
        
      <input type="hidden" name="_method" value="DELETE">

      <input type="submit" value="Logout">
    </form>
    <% end %>
    
    
    <%= yield %>

    <%= yield :footer%>
  </body>
</html>

app/views/users/edit.html.erb
<h1>This is where you edit <%= @user.email %>! </h1>

app/views/users/index.html.erb
<a href="<%= new_session_url %>">Log-in</a>
<p>or</p>
<a href="<%= new_user_url %>">Sign-up</a>


<h3>Users</h3>
<% User.all.each do |user| %>

 <p> <a href="<%= user_url(user) %> "> <%= user.email %> </a> </p>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up!</h1>

<form action="<%= users_url %>" method="POST">
     <input 
        type="hidden" 
        name="authenticity_token" 
        value="<%= form_authenticity_token %>">
 
    <label for="user_email">Email:</label>
    <input type="text" name="user[email]" id="user_email">
    <br>

    <label for="user_password">Password:</label>
    <input type="password" name="user[password]" id="user_password">
    <br>

    <input type="submit" value="Create!">
</form>

app/views/users/show.html.erb
<h2> <%= @user.email %>'s Profile </h2>

<% if !@user.comments.nil? %>
  <% @user.comments.each do |comment| %>
    <p> <%= comment.body %> <p>
  <% end %>
<% end %>

<%= render 'comments/new', commentable: @user %>

<h3> <%= @user.email %>'s Goals: </h3>

<a href="<%= new_goal_url %>">New Goal</a>
  <% @user.goals.each do |goal| %>
  <p> 
    <a href="<%= goal_url(goal) %>"><%= goal.title %></a>
    <p> <%= goal.private?  ? "Private" : "Public"%></p>
    <p> <%= goal.completed  ? "Completed" : "Ongoing"%></p>


    <% if current_user.id == goal.user_id %>
    <%= render 'goals/edit', goal: goal %>
    <%= render 'goals/delete', goal: goal %>
    <% end %>

  </p>
  <% end %>

<%= content_for :footer do %>
  <form action="<%= users_url %>" method="GET">
    <input type="submit" value="All Users">
  </form>
<% end %>